### Matching descriptions from CIVITATIS activities

In this script I take some activities from CIVITATIS that have mistakes in the description columns and correct them using the infomartion from the CIVITATIS API.

In [1]:
# Install and import packages
import pandas as pd
import numpy as np

Load the table with mistakes and clean it

In [2]:
# Sample taken from the civitatis_activities table
df_err=pd.read_excel("C:/Users/beder/Desktop/Data 2022/Projects/CIVITATIS-IMPLEMENTATION2022/Project Files/inputs/20221229_civitatis_erros.xlsx")
df_err.shape

(2805, 7)

In [4]:
df_err=df_err[['civitatis_activity_id', 'civitatis_id', 'destination_civitatis_id',
       'city_id', 'place_id']]

In [5]:
df_err

,civitatis_activity_id,civitatis_id,destination_civitatis_id,city_id,place_id
0,267,112260,1237,100157,33
1,268,99402,1237,100157,33
2,269,99170,1237,100157,33
3,271,53647,1237,100157,33
4,272,52933,1237,100157,33
...,...,...,...,...,...
2800,3131,8201,93,100130,4758
2801,3132,8135,93,100130,4758
2802,3133,8093,93,100130,4758
2803,3135,147532,4600,300009,7362
2804,3136,141888,4600,300009,7362

Load the table with information in english

In [6]:
df_engl=pd.read_csv('C:/Users/beder/Desktop/Data 2022/Projects/CIVITATIS-IMPLEMENTATION2022/Outputs/Civitatis Exctraction/all_activities30_12_2022.csv')
df_engl.columns

C:\Users\beder\AppData\Local\Temp\ipykernel_19336\1777980541.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_engl=pd.read_csv('C:/Users/beder/Desktop/Data 2022/Projects/CIVITATIS-IMPLEMENTATION2022/Outputs/Civitatis Exctraction/all_activities30_12_2022.csv')

Index(['id', 'type', 'lang', 'destinationId', 'title', 'voucherType',
       'relatedActivities', 'score', 'reviews', 'url', 'description',
       'raw_description', 'photos', 'typologies', 'category', 'subcategory',
       'amountType', 'minimumPrice', 'isFreeTour', 'currency', 'originalPrice',
       'included', 'notIncluded', 'cancelPolicy', 'cancelPolicies',
       'MinimumPaxPerBooking', 'infoVoucher', 'duration', 'advance', 'address',
       'accessibility', 'rates', 'longitude', 'latitude'],
      dtype='object')

In [7]:
df_engl=df_engl[['id','title','description']]
df_engl.head(20)

,id,title,description
0,151145,Venecian Carnival Tour,The<strong> history of the Venice Carnival </s...
1,150897,Vivaldi's Four Seasons Concert,<strong>Attend a concert of Antonio Vivaldi's ...
2,142543,Verona Train Trip,"If you're in <strong>Venice</strong>, you'll l..."
3,140553,Venice Boat Rental with Skipper,<p>Want to <strong>sail around the city of can...
4,140509,San Marco City Pass,The<strong> San Marco City Pass</strong> inclu...
5,139427,Luxury Dinner + Avanspettacolo Venezia Cabaret...,If you want to enjoy <strong>an unforgettable ...
6,137255,Venice Islands Private Day Trip,"On our&nbsp;Venice Islands Private Day Trip, y..."
7,137250,Venice Walking Theater Show,"<p>On this dramatized tour of Venice, we'll <s..."
8,132065,Venice Legends & Mysteries Free Tour,Get a first taste of the City of Water on our ...
9,127350,Venice Galleon Cruise & Lunch,On our <strong>Venice Galleon Cruise &amp; Lun...
10,125413,Hard Rock CafeÂ Venice,<b>Come to the iconic Hard Rock Cafe Venice </...
11,124811,Venice Glass Workshop Experience,"<b>Did you know Venice is known for its 1,000-..."
12,124806,Venice Carnival Mask: Make Your Own,"Venice, the city of canals... and Carnival!<b>..."
13,123139,Doge's Palace Prison Concert,The prison of the Doge's Palace is the perfect...
14,121779,Stairs of the Palazzo Contarini del Bovolo Ticket,The ticket to the Palazzo Contarini del Bovolo...
15,121764,Peggy Guggenheim Collection Ticket,Visit <b>one of the most important galleries o...
16,110370,Castello Neighbourhood Tour,<b>Explore the largest neighborhood in Venice ...
17,109750,Offer: St. Mark's Basilica + Doge's Palace Tour,Explore two of Venice's famous monuments with ...
18,106422,Venice Glass Workshop,Discover the secrets of this <b>ancient craft ...
19,105720,Palazzo delle Prigioni Tour,On this <b>guided tour to Palazzo delle Prigio...

In [8]:
#df_engl.duplicated('id')
ids=df_engl['id']
df_engl[ids.isin(ids[ids.duplicated()])].sort_values("id")

,id,title,description
1844,1158,Guided Jet-Ski Experience,Live a <strong>unique and unforgettable experi...
14149,1158,Guided Jet-Ski Experience,Live a <strong>unique and unforgettable experi...
14166,1158,Guided Jet-Ski Experience,Live a <strong>unique and unforgettable experi...
16081,4183,Go City: Oahu All-Inclusive Pass,The <strong>Go City: Oahu All-Inclusive Pass</...
16305,4183,Go City: Oahu All-Inclusive Pass,The <strong>Go City: Oahu All-Inclusive Pass</...
...,...,...,...
7611,154092,Calanques de Piana Speedboat Tour,On this <strong>speedboat tour of the Calanque...
7609,154335,Calanques de Piana Sunset Boat Ride,During this <strong>evening boat trip to the C...
7614,154335,Calanques de Piana Sunset Boat Ride,During this <strong>evening boat trip to the C...
16437,154416,Stargazing in Oudtshoorn,In this <strong>stargazing activity in Oudtsho...
6897,154416,Stargazing in Oudtshoorn,In this <strong>stargazing activity in Oudtsho...

In [9]:
df_engl=df_engl.drop_duplicates()
df_engl.shape

(14365, 3)

In [10]:
# Merge both tables and keep only ids of df_err
df_err_engl=df_err.merge(df_engl, how='left',left_on='civitatis_id',right_on='id')
df_err_engl.shape

(2805, 8)

In [11]:
df_err_engl=df_err_engl.rename(columns={'id':'id_english','title':'name_en','description':'description_en'})
df_err_engl

,civitatis_activity_id,civitatis_id,destination_civitatis_id,city_id,place_id,id_english,name_en,description_en
0,267,112260,1237,100157,33,NaN,NaN,NaN
1,268,99402,1237,100157,33,NaN,NaN,NaN
2,269,99170,1237,100157,33,NaN,NaN,NaN
3,271,53647,1237,100157,33,NaN,NaN,NaN
4,272,52933,1237,100157,33,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2800,3131,8201,93,100130,4758,8201.0,Party in Coco Bongo,"Spend a memorable night at <b>Coco Bongo, one ..."
2801,3132,8135,93,100130,4758,8135.0,Tulum + Mayan Village Tour,"On this excursion to Tulum, visit <strong>one ..."
2802,3133,8093,93,100130,4758,8093.0,Ek Balam Day Trip,On this <strong>excursion to Ek Balam</strong>...
2803,3135,147532,4600,300009,7362,NaN,NaN,NaN
2804,3136,141888,4600,300009,7362,NaN,NaN,NaN

Load activities in spanish

In [12]:
df_es=pd.read_csv('C:/Users/beder/Desktop/Data 2022/Projects/CIVITATIS-IMPLEMENTATION2022/Outputs/Civitatis Exctraction/all_activities30_12_2022_es.csv')
df_es.columns

Index(['id', 'type', 'lang', 'destinationId', 'title', 'voucherType',
       'relatedActivities', 'score', 'reviews', 'url', 'description',
       'raw_description', 'photos', 'typologies', 'category', 'subcategory',
       'amountType', 'minimumPrice', 'isFreeTour', 'currency', 'originalPrice',
       'included', 'notIncluded', 'cancelPolicy', 'cancelPolicies',
       'MinimumPaxPerBooking', 'infoVoucher', 'duration', 'advance', 'address',
       'accessibility', 'rates', 'longitude', 'latitude'],
      dtype='object')

In [13]:
df_es=df_es[['id','title','description']]
df_es=df_es.drop_duplicates()
df_es.shape

(17669, 3)

In [14]:
df_err_engl_es=df_err_engl.merge(df_es, how='left',left_on='civitatis_id',right_on='id')
df_err_engl_es.shape

(2805, 11)

In [15]:
df_err_engl_es

,civitatis_activity_id,civitatis_id,destination_civitatis_id,city_id,place_id,id_english,name_en,description_en,id,title,description
0,267,112260,1237,100157,33,NaN,NaN,NaN,112260.0,Entrada al castillo de la ConcepciÃ³n + Ascenso...,Con esta <b>entrada al castillo de la Concepci...
1,268,99402,1237,100157,33,NaN,NaN,NaN,99402.0,Visita guiada por el Museo Naval + Paseo en barco,<b>Descubre todos los secretos y anÃ©cdotas del...
2,269,99170,1237,100157,33,NaN,NaN,NaN,99170.0,Tour de tapas por Cartagena,<b>La mejor forma de conocer la historia y per...
3,271,53647,1237,100157,33,NaN,NaN,NaN,53647.0,Tour privado por Cartagena,Revive <b>el pasado romano de Cartagena y desc...
4,272,52933,1237,100157,33,NaN,NaN,NaN,52933.0,Tour por la Cartagena modernista,Disfruta de esta visita guiada por el <b>casco...
...,...,...,...,...,...,...,...,...,...,...,...
2800,3131,8201,93,100130,4758,8201.0,Party in Coco Bongo,"Spend a memorable night at <b>Coco Bongo, one ...",NaN,NaN,NaN
2801,3132,8135,93,100130,4758,8135.0,Tulum + Mayan Village Tour,"On this excursion to Tulum, visit <strong>one ...",NaN,NaN,NaN
2802,3133,8093,93,100130,4758,8093.0,Ek Balam Day Trip,On this <strong>excursion to Ek Balam</strong>...,NaN,NaN,NaN
2803,3135,147532,4600,300009,7362,NaN,NaN,NaN,147532.0,Paseo en barco transparente por Isla Mujeres,En este paseo en barco transparente por Isla M...
2804,3136,141888,4600,300009,7362,NaN,NaN,NaN,141888.0,Entrada al Parque Natural GarrafÃ³n,"<strong>Relax, cultura y aventura</strong> son..."

In [16]:
df_err_engl_es=df_err_engl_es.rename(columns={'id':'id_espa','title':'name_es','description':'description_es'})
df_err_engl_es

,civitatis_activity_id,civitatis_id,destination_civitatis_id,city_id,place_id,id_english,name_en,description_en,id_espa,name_es,description_es
0,267,112260,1237,100157,33,NaN,NaN,NaN,112260.0,Entrada al castillo de la ConcepciÃ³n + Ascenso...,Con esta <b>entrada al castillo de la Concepci...
1,268,99402,1237,100157,33,NaN,NaN,NaN,99402.0,Visita guiada por el Museo Naval + Paseo en barco,<b>Descubre todos los secretos y anÃ©cdotas del...
2,269,99170,1237,100157,33,NaN,NaN,NaN,99170.0,Tour de tapas por Cartagena,<b>La mejor forma de conocer la historia y per...
3,271,53647,1237,100157,33,NaN,NaN,NaN,53647.0,Tour privado por Cartagena,Revive <b>el pasado romano de Cartagena y desc...
4,272,52933,1237,100157,33,NaN,NaN,NaN,52933.0,Tour por la Cartagena modernista,Disfruta de esta visita guiada por el <b>casco...
...,...,...,...,...,...,...,...,...,...,...,...
2800,3131,8201,93,100130,4758,8201.0,Party in Coco Bongo,"Spend a memorable night at <b>Coco Bongo, one ...",NaN,NaN,NaN
2801,3132,8135,93,100130,4758,8135.0,Tulum + Mayan Village Tour,"On this excursion to Tulum, visit <strong>one ...",NaN,NaN,NaN
2802,3133,8093,93,100130,4758,8093.0,Ek Balam Day Trip,On this <strong>excursion to Ek Balam</strong>...,NaN,NaN,NaN
2803,3135,147532,4600,300009,7362,NaN,NaN,NaN,147532.0,Paseo en barco transparente por Isla Mujeres,En este paseo en barco transparente por Isla M...
2804,3136,141888,4600,300009,7362,NaN,NaN,NaN,141888.0,Entrada al Parque Natural GarrafÃ³n,"<strong>Relax, cultura y aventura</strong> son..."

Clean strange characters in the description

In [17]:
# Replace strange characters in description_es and description_en

char=['<strong>','<p>','</p>','</strong>','<b>','</b>','</em>','&nbsp','&amp','<em>',';']

for i in char:
    df_err_engl_es['description_es'] = df_err_engl_es['description_es'].str.replace(i,' ')
    df_err_engl_es['description_en'] = df_err_engl_es['description_en'].str.replace(i,' ')


df_err_engl_es.head(20)

,civitatis_activity_id,civitatis_id,destination_civitatis_id,city_id,place_id,id_english,name_en,description_en,id_espa,name_es,description_es
0,267,112260,1237,100157,33,NaN,NaN,NaN,112260.0,Entrada al castillo de la ConcepciÃ³n + Ascenso...,Con esta entrada al castillo de la ConcepciÃ³n...
1,268,99402,1237,100157,33,NaN,NaN,NaN,99402.0,Visita guiada por el Museo Naval + Paseo en barco,Descubre todos los secretos y anÃ©cdotas del P...
2,269,99170,1237,100157,33,NaN,NaN,NaN,99170.0,Tour de tapas por Cartagena,La mejor forma de conocer la historia y perso...
3,271,53647,1237,100157,33,NaN,NaN,NaN,53647.0,Tour privado por Cartagena,Revive el pasado romano de Cartagena y descub...
4,272,52933,1237,100157,33,NaN,NaN,NaN,52933.0,Tour por la Cartagena modernista,Disfruta de esta visita guiada por el casco h...
5,273,50221,1237,100157,33,NaN,NaN,NaN,50221.0,Free tour por Cartagena,Disfrutaremos de Cartagena con este free tour...
6,274,41815,1237,100157,33,NaN,NaN,NaN,41815.0,Visita guiada por Cartagena,Cartagineses y romanos dejaron su impronta en ...
7,275,33217,1237,100157,33,NaN,NaN,NaN,33217.0,Tour de los misterios y leyendas de Cartagena,"Fantasmas que pasean por las calles, asesinato..."
8,276,32710,1237,100157,33,NaN,NaN,NaN,32710.0,Tour por la Cartagena masÃ³nica,Descubre todos los secretos de la masonerÃ­a en...
9,278,130466,1237,100157,33,130466.0,Cartagena Augusteum Ticket,Travel back in time to the splendour of Roman...,NaN,NaN,NaN
10,279,129866,1237,100157,33,129866.0,Cartagena Sightseeing Tour,"On this Cartagena Sightseeing Tour , you'll e...",NaN,NaN,NaN
11,280,129101,1237,100157,33,129101.0,Cartagena House of Fortune Ticket,If you're in Cartagena love ancient history...,NaN,NaN,NaN
12,281,129099,1237,100157,33,129099.0,Cartagena Civil War Shelters Museum Ticket,With our Cartagena Civil War Shelters Museum ...,NaN,NaN,NaN
13,282,129097,1237,100157,33,129097.0,Cartagena Punic Wall Interpretation Centre Ticket,Discover the history of the Punic Wars with ...,NaN,NaN,NaN
14,283,117285,1237,100157,33,117285.0,Cartagena Archaelogical Combo Ticket,With this ticket you can visit Cartagena's Mu...,NaN,NaN,NaN
15,284,115437,1237,100157,33,115437.0,Cartagena Roman Theatre Museum Ticket,Delve into Carthago Nova's Roman past by re...,NaN,NaN,NaN
16,285,114470,1237,100157,33,114470.0,Molinete Roman Forum Museum Ticket,Travel the ancient Roman roads and buildings ...,NaN,NaN,NaN
17,286,114437,1237,100157,33,114437.0,Castillo de la ConcepciÃ³n and Panoramic Lift,Enjoy fabulous views of Cartagena and its port...,NaN,NaN,NaN
18,287,51445,1237,100157,33,51445.0,Cartagena Free Walking Tour,Discover beautiful Cartagena when you take ou...,NaN,NaN,NaN
19,288,44245,1237,100157,33,44245.0,Guided Walking Tour of Cartagena,Carthaginians and RomansÂ left their mark on th...,NaN,NaN,NaN

In [18]:
df_err_engl_es.to_csv('C:/Users/beder/Desktop/Data 2022/Projects/CIVITATIS-IMPLEMENTATION2022/Outputs/Civitatis Exctraction/civitatis_descrptn_err_solved_2.csv')