In [25]:
import pandas as pd
import geopandas
from shapely.geometry import Point, Polygon, LineString

import glob
import os
import matplotlib.pyplot as plt


from datetime import datetime
from shapely.geometry import Point, Polygon, LineString
import matplotlib.pyplot as plt
import os
from IPython.display import clear_output

from pymysql import*
import xlwt
import pandas.io.sql as sql
import time
import datetime
import googlemaps
import unittest

# Place_ID Refresh in Spots

## Load spots

In [11]:
con=connect(user="beder",password="hTz8@A6Yn652",host="server.digizonelabs.com",database="beder_appprod")
spots=sql.read_sql('select * from beder_appprod.spots',con)

c:\Users\beder\.conda\envs\ACTIMPLE2022\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [12]:
spots

,spot_id,country_id,region_id,province_id,city_id,google_api_level,google_id,english_name,spanish_name,top_spot_level_1,...,attractions,beach,food,nightlife,arts_and_culture,accomodation,created_at,updated_at,latitude,longitude
0,1,62,579.0,1422.0,670.0,None,ChIJs_XbU7PxR5kR9i7G2WBgDH0,Моаї,Moáis,1.0,...,None,None,None,None,None,None,2021-11-15 15:42:04,2021-11-15 15:42:04,NaN,NaN
1,2,62,578.0,1419.0,684.0,None,ChIJ38C5J5wxqpYR3KgH73H_KNY,El Tatio Geysers,Géiseres del Tatio,1.0,...,None,None,None,None,None,None,2021-11-15 15:42:04,2021-11-15 15:42:04,NaN,NaN
2,3,62,579.0,1422.0,670.0,None,ChIJO2UGYFbuR5kRuPUng4wGFNI,Anakena Beach,Playa Anakena,1.0,...,None,None,None,None,None,None,2021-11-15 15:42:04,2021-11-15 15:42:04,NaN,NaN
3,4,62,586.0,2377.0,688.0,None,ChIJRb35MfNIsr0RkjMaxmZG8IQ,Los Pingüinos Natural Monument,Monumento Natural Los Pingüinos,1.0,...,None,None,None,None,None,None,2021-11-15 15:42:04,2021-11-15 15:42:04,NaN,NaN
4,5,62,583.0,1429.0,689.0,None,ChIJq83JsR6fPZYRCiaj9Qjnqk8,Caleta Condor Beach,Playa de Caleta Cóndor,NaN,...,None,None,None,None,None,None,2021-11-15 15:42:04,2021-11-15 15:42:04,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8432,12005181,56,NaN,890.0,1200307.0,None,ChIJO_YCqBgTRw0RK8DGaMCdkjY,"Ruta turistica ""Valladolid Monumental""","Ruta turistica ""Valladolid Monumental""",0.0,...,None,None,None,None,None,None,2022-06-12 20:43:51,2021-11-15 15:42:04,41.6569,-4.72447
8433,12005182,56,NaN,890.0,1200307.0,None,ChIJX3JwTrUSRw0RqGsCIBK0Tck,Monumento a Colón,Monumento a Colón,0.0,...,None,None,None,None,None,None,2022-06-12 20:43:51,2021-11-15 15:42:04,41.6445,-4.72739
8434,12005183,56,NaN,890.0,1200307.0,None,ChIJNad_GrASRw0R8rSIDt-pIAo,Casa Museo Colón,Casa Museo Colón,0.0,...,None,None,None,None,None,None,2022-06-12 20:43:51,2021-11-15 15:42:04,41.6535,-4.71818
8435,12005184,56,NaN,890.0,1200307.0,None,ChIJUwBbfk5tRw0RxYJ0fUGAowo,La Rosaleda,La Rosaleda,0.0,...,None,None,None,None,None,None,2022-06-12 20:43:51,2021-11-15 15:42:04,41.6530,-4.73283
8436,12005185,56,NaN,890.0,1200307.0,None,ChIJiwE3OKwSRw0RL_-om4iqNRs,Museo Nacional de Escultura,Museo Nacional de Escultura,0.0,...,None,None,None,None,None,None,2022-06-12 20:43:51,2021-11-15 15:42:04,41.6572,-4.72371

## Call API

In [32]:
gmaps = googlemaps.Client(key='AIzaSyCZYMiHXX_OPFziNiqgUmkxrHbCbfiaLKw')
try:
    gmaps.place(place_id='ChIJ8Xhlw19PTg0R-pMIOOCnT2w')
except:
    pass

In [33]:
lats = []
lng = []
for i, place_id in enumerate(spots['google_id']):  
    time.sleep(0.5)
    clear_output(wait=True)
    print(i,place_id,flush = True)    
    try:
        results = gmaps.place(place_id)
        if results == None:
            lats.append(0)
            lng.append(0)
        else:
            lats.append(results['result']['geometry']['location']['lat'])
            lng.append(results['result']['geometry']['location']['lng'])
    except:
        lats.append(0)
        lng.append(0)

8436 ChIJiwE3OKwSRw0RL_-om4iqNRs

In [34]:
spots['latitude'] = lats
spots['longitude'] = lng

In [36]:
spots.to_csv('spots_loc_updated')